In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([3,1,5])

In [4]:
a

array([3, 1, 5])

In [6]:
a.shape

(3,)

In [7]:
b = np.arange(15).reshape(3,5)

In [8]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
b.shape

(3, 5)

In [10]:
b.dtype

dtype('int32')

In [11]:
b.size

15

In [12]:
n = 1
m = 2

p = n + m
p

3

In [13]:
a = [1,2,3]
b = [2,3,4]

c = a + b
c

[1, 2, 3, 2, 3, 4]

In [14]:
c = a - b
c

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [18]:
a1 = np.array([1,2,3])
b1 = np.array([2,3,4])
a1+b1

array([3, 5, 7])

In [19]:
data = {'Animal': ['Dog',  'Orangutan', 'Eagle','Pandas', "Elephant"],
        'Name': ['Ellen',  'Adam',  'Joe', 'Eve','Eve'],
        'Legs': [4, 2, 1, 3,4],
        'IsNice': [1,0,0,0,1]}

df = pd.DataFrame(data, columns=['Animal', 'Name', 'Legs', 'IsNice'])

In [20]:
df

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
1  Orangutan   Adam     2       0
2      Eagle    Joe     1       0
3     Pandas    Eve     3       0
4   Elephant    Eve     4       1

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
Animal    5 non-null object
Name      5 non-null object
Legs      5 non-null int64
IsNice    5 non-null int64
dtypes: int64(2), object(2)
memory usage: 160.0+ bytes


In [25]:
from pandas.io.json import json_normalize
dfx = [{'id': 1, 'name': {'first': 'Anna', 'last': 'Rich'}},
         {'name': {'given': 'Anna', 'family': 'Broke'}},
         {'id': 2, 'name': {'first': 'Anna', 'last': 'Here'}}]


c = json_normalize(dfx)

In [26]:
c.shape

(3, 5)

In [27]:
c.columns

Index(['id', 'name.family', 'name.first', 'name.given', 'name.last'], dtype='object')

In [28]:
c.describe(include = 'all')

id name.family name.first name.given name.last
count   2.000000           1          2          1         2
unique       NaN           1          1          1         2
top          NaN       Broke       Anna       Anna      Rich
freq         NaN           1          2          1         1
mean    1.500000         NaN        NaN        NaN       NaN
std     0.707107         NaN        NaN        NaN       NaN
min     1.000000         NaN        NaN        NaN       NaN
25%     1.250000         NaN        NaN        NaN       NaN
50%     1.500000         NaN        NaN        NaN       NaN
75%     1.750000         NaN        NaN        NaN       NaN
max     2.000000         NaN        NaN        NaN       NaN

In [29]:
df.describe(include = 'all')

Animal Name     Legs    IsNice
count       5    5  5.00000  5.000000
unique      5    4      NaN       NaN
top     Eagle  Eve      NaN       NaN
freq        1    2      NaN       NaN
mean      NaN  NaN  2.80000  0.400000
std       NaN  NaN  1.30384  0.547723
min       NaN  NaN  1.00000  0.000000
25%       NaN  NaN  2.00000  0.000000
50%       NaN  NaN  3.00000  0.000000
75%       NaN  NaN  4.00000  1.000000
max       NaN  NaN  4.00000  1.000000

In [30]:
df2 = pd.read_csv('C:\Users\Haoxiang_Weng\greenfox\TemExile\week-06\day-1\googleplaystore.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-30-19563064eed9>, line 1)

In [32]:
sorted = df.sort_values(by = ['Legs'], ascending = False)

In [33]:
sorted

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
4   Elephant    Eve     4       1
3     Pandas    Eve     3       0
1  Orangutan   Adam     2       0
2      Eagle    Joe     1       0

In [34]:
sorted[1:]

Animal  Name  Legs  IsNice
4   Elephant   Eve     4       1
3     Pandas   Eve     3       0
1  Orangutan  Adam     2       0
2      Eagle   Joe     1       0

In [36]:
sorted[:3]

Animal   Name  Legs  IsNice
0       Dog  Ellen     4       1
4  Elephant    Eve     4       1
3    Pandas    Eve     3       0

In [37]:
sorted.iloc[[0],[0]]

Animal
0    Dog

In [39]:
sorted.loc[[0], ['Name']]

Name
0  Ellen

In [40]:
df[df['Legs'] > 2]

Animal   Name  Legs  IsNice
0       Dog  Ellen     4       1
3    Pandas    Eve     3       0
4  Elephant    Eve     4       1

In [41]:
df[(df['Legs'] > 2) & (df['Name'] == 'Eve')][['Animal', 'Legs']]

Animal  Legs
3    Pandas     3
4  Elephant     4

In [42]:
df[df['Legs'].isin([4,2])]

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
1  Orangutan   Adam     2       0
4   Elephant    Eve     4       1

In [43]:
df['Flock'] = df['Legs'] * 12

In [44]:
df

Animal   Name  Legs  IsNice  Flock
0        Dog  Ellen     4       1     48
1  Orangutan   Adam     2       0     24
2      Eagle    Joe     1       0     12
3     Pandas    Eve     3       0     36
4   Elephant    Eve     4       1     48

In [45]:
df = df.drop(['Name'], axis = 1)

In [46]:
df

Animal  Legs  IsNice  Flock
0        Dog     4       1     48
1  Orangutan     2       0     24
2      Eagle     1       0     12
3     Pandas     3       0     36
4   Elephant     4       1     48

In [47]:
def yes_no_record(value):
    record = np.where(value == 1, 'Yes', 'No')
    return record
df['IsNiceRecord'] = df['IsNice'].apply(yes_no_record)

In [48]:
df

Animal  Legs  IsNice  Flock IsNiceRecord
0        Dog     4       1     48          Yes
1  Orangutan     2       0     24           No
2      Eagle     1       0     12           No
3     Pandas     3       0     36           No
4   Elephant     4       1     48          Yes

In [49]:
df.to_csv('new_animal.csv')